[book]
title = "Rust By Example"
description = "Rust by Example (RBE) is a collection of runnable examples that illustrate various Rust concepts and standard libraries."
author = "The Rust Community"

[output.html.fold]
enable = true

[output.html]
git-repository-url = "https://github.com/rust-lang/rust-by-example"
base-url = "https://vendestine.github.io/blog-mdbook"

[rust]
edition = "2021"

[preprocessor.gettext]
after = ["links"]

[preprocessor.yml-header]

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[preprocessor.katex]
after = ["links"]